# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - snyk-azure-pipelines

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk-azure-devops'
    testType: 'code'
    failOnIssues: true
    projectName: 'juice-shop-goof'
    organization: 'snyk-certification-2025-anand'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk-azure-devops'
    testType: 'command'
    command: 'sbom test'
    failOnIssues: true
    projectName: 'juice-shop-goof'
    organization: 'snyk-certification-2025-anand'
